name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests for Vehicle Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7.0.6

      - name: Start gRPC Server
        run: |
          npm run start > grpc.log 2>&1 &
          sleep 10
          echo "gRPC log:"
          cat grpc.log
        env:
          MONGO_URI: mongodb+srv://pts-user:pts-user@clusterpts.ihmpmb6.mongodb.net/VehicleDB?retryWrites=true&w=majority

      - name: Run Tests
        run: npm test
